version: '2'
services:
    app:
        image: registry.spin.nersc.gov/bweaver/spin-lesson-1-app:latest
        cap_drop:
            - ALL
    web:
        image: registry.spin.nersc.gov/bweaver/spin-lesson-1-nginx:latest
        ports:
            - "60040:8080"
        volumes:
            - /global/project/projectdirs/desi/users/bweaver/spin-lesson-1/web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        user: 34448:58102
        group_add:
            - nginx
        cap_drop:
            - ALL
