version: '2'
services:
    app:
        image: registry.spin.nersc.gov/bweaver/distributor-app:latest
        volumes:
            - /global/project/projectdirs/desi/users/bweaver/distributor/app/desi:/opt/app/desi:ro
        user: 34448:58102
        environment:
            DESI_SPECTRO_REDUX: /opt/app/desi/spectro/redux
            SPECPROD: mini
        cap_drop:
            - ALL
    web:
        image: registry.spin.nersc.gov/bweaver/distributor-nginx:latest
        # image: nginx-rootless:v1
        ports:
            - "60040:8080"
        volumes:
            - /global/project/projectdirs/desi/users/bweaver/distributor/web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        user: 34448:58102
        # group_add:
        #     - nginx
        cap_drop:
            - ALL
